// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFZ8FdMuEcveASUgRsMoGfqDjhGLxBXW4',
    appId: '1:158358325466:web:1844553f3a748dca153de3',
    messagingSenderId: '158358325466',
    projectId: 'clubeventform',
    authDomain: 'clubeventform.firebaseapp.com',
    storageBucket: 'clubeventform.appspot.com',
    measurementId: 'G-YF80YXC42N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1ryriHZwBS5lpe7OzMZu4sjIm39i2Rw',
    appId: '1:158358325466:android:852eaa97afd40c67153de3',
    messagingSenderId: '158358325466',
    projectId: 'clubeventform',
    storageBucket: 'clubeventform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCCeeBaSYq1LmraQdP9DdBFftNtxqo0fU',
    appId: '1:158358325466:ios:4c7e98869965bc72153de3',
    messagingSenderId: '158358325466',
    projectId: 'clubeventform',
    storageBucket: 'clubeventform.appspot.com',
    iosClientId: '158358325466-5gt96um8vh9gd56j4hvh9ke0psr6iemh.apps.googleusercontent.com',
    iosBundleId: 'com.example.legion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCCeeBaSYq1LmraQdP9DdBFftNtxqo0fU',
    appId: '1:158358325466:ios:4c7e98869965bc72153de3',
    messagingSenderId: '158358325466',
    projectId: 'clubeventform',
    storageBucket: 'clubeventform.appspot.com',
    iosClientId: '158358325466-5gt96um8vh9gd56j4hvh9ke0psr6iemh.apps.googleusercontent.com',
    iosBundleId: 'com.example.legion',
  );
}
